apiVersion: apps/v1
kind: Deployment
metadata:
  name: mergequeue-deployment
spec:
  selector:
    matchLabels:
      app: mergequeue
  template:
    metadata:
      labels:
        app: mergequeue
    spec:
      containers:
        - name: mergequeue
          image: mergequeue:v1.3.1
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
          env:
            - name: MongoDbSettings__Host
              value: mongodb-service
            - name: MongoDbSettings__Password
              valueFrom:
                secretKeyRef:
                  name: mergequeue-secrets
                  key: mongodb-password
            - name: SlackApiSettings__BotToken
              valueFrom:
                secretKeyRef:
                  name: mergequeue-secrets
                  key: slackapi-bottoken
            - name: SlackApiSettings__SigningSecret
              valueFrom:
                secretKeyRef:
                  name: mergequeue-secrets
                  key: slackapi-signingsecret

---
apiVersion: v1
kind: Service
metadata:
  name: mergequeue-service
spec:
  type: LoadBalancer
  selector:
    app: mergequeue
  ports:
    - port: 46001
      targetPort: 80
